steps:

  # Upload dataflow pipeline to GCS.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'dataflow_pipeline', 'gs://bucket_cs_mlops']
    id:  'upload'
    waitFor: ['compile']

  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Compile pipeline
  - name: 'python'
    entrypoint: 'python'
    args: ['pipeline.py']
    id: 'compile'

  # Upload compiled pipeline to GCS.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'ml_glassclassification.json', 'gs://bucket_cs_mlops']
    id:  'upload'
    waitFor: ['compile']